# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jueen
tagline:          'A personal intro'
description:      'A personal intro'
url:              http://jueen.github.io/
baseurl:          http://jueen.github.io/

author:
  name:           'Jueen Lee'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jueen/hyde
